AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'config.ru'
    - 'node_modules/**/*'
    - '.git/**/*'
    - 'Rakefile'
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'lib/**/*'
    - 'log/**/*'
    - 'script/**/*'
    - 'spec/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'

Style/Documentation:
  Enabled: false

Style/DocumentationMethod:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

