language: ruby
rvm:
 - 2.5.1
cache: bundler
services:
  - postgresql
before_script:
  - npm install yarn
  - ./bin/webpack
  - gem install rubocop
  - bundle exec rake db:create db:schema:load db:migrate
script:
  - rubocop
  - bin/rake
